### 8803 : Data Analytics 

In [1]:
negativeList=open('data/neg_examples_sad.txt').read().splitlines()
positiveList=open('data/pos_examples_happy.txt').read().splitlines()
#print negativeList
#print len(positiveList)


In [2]:
#remove #sad and #happy

negativeListCopy=[]
for i in negativeList:   
    i = i.lower()
    if "#sad" in i:
        i=i.replace("#sad","")
    negativeListCopy.append(i)
positiveListCopy=[]       
for i in positiveList:
    i=i.lower()
    if "#happy" in i:
        i=i.replace("#happy","")
    positiveListCopy.append(i)
print positiveListCopy[:5]
print negativeListCopy[:5]
  

['rt @trvlgenieapp: retweet to win #travel prizes! #genie plans #itinerary 4u #love #fun #f4f #sun #beach  https://t.co/dnyyzqjcex http', 'relax   #fun #park #loveit #sisters https://t.co/u20sezdwlw', '@trvlgenieapp #travel #genie #itinerary #love #fun #f4f #sun #beach  woohoo awesome giveaway ! thank you for the  amazing chance ', 'rt @f5fitnessla: humans mirror naturally. put forth what you want reflected. #beagoodmirror #positiveattitude #smilesforeveryone #fitnessmo', '#love #couple #couplegoals #couples #cute #girlfriend #boyfriend  #like4like #inlove #relationshipgoals #love https://t.co/avgu2tikkt']
["rt @saffronkim: i just can't understand how people can believe that blowing up their fellow humans is somehow an act of anything other than", '@etvumlilo i missed it ', '#traditional #tradionaltattoo #traditionaltattoos  #marinero #chile #chiletattoo #diseodisponible #diseodispo https://t.co/y1firrim0v', 'dios qu hambre ahora quiero un bocadillo de calamares :(( ', 'rip brussels vi

In [3]:
import re
#remove urls, RT tokens and @ tokens.
negativeCopy=[]
positiveCopy=[]
for i in range(len(negativeListCopy)):
    if negativeListCopy[i].lower().startswith("rt"):
    #         negativeListCopy[i]=negativeListCopy[i].replace("rt","")
        continue
    negativeListCopy[i]=re.sub(r"http\S+","",negativeListCopy[i]) 
    negativeListCopy[i]=' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)"," ",negativeListCopy[i]).split())
    negativeCopy.append(negativeListCopy[i])
print negativeCopy[0:5] 
negativeListCopy=negativeCopy
for i in range(len(positiveListCopy)):
    if "rt" in positiveListCopy[i]:
        continue
    positiveListCopy[i]=re.sub(r"http\S+","",positiveListCopy[i])
    positiveListCopy[i]=' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)"," ",positiveListCopy[i]).split())
    positiveCopy.append(positiveListCopy[i])
positiveListCopy=positiveCopy
print positiveListCopy[0:5]


['i missed it', 'traditional tradionaltattoo traditionaltattoos marinero chile chiletattoo diseodisponible diseodispo', 'dios qu hambre ahora quiero un bocadillo de calamares', 'rip brussels victims why justdontgetit whatswiththehatred brusselsattack', 'terrible brussels']
['relax fun park loveit sisters', 'travel genie itinerary love fun f4f sun beach woohoo awesome giveaway thank you for the amazing chance', 'love couple couplegoals couples cute girlfriend boyfriend like4like inlove relationshipgoals love', 'you need to learn to be by nature because you ll seldom have the chance to be by circumstance lavetta sue wegman', 'weekend before weekend twodaysholiday']


In [4]:
# %load LIWCMeta.py

"""
Created on Fri Mar 01 13:35:34 2016

@author: Sarthak Ghosh
"""

print positiveListCopy[0:5]

import re

def getLex(post, liwc_lexicons):
	liwc_lexicon_to_count = {}
	for liwc_lexicon_name in set(liwc_lexicons.keys()):
		liwc_lexicon_to_count[liwc_lexicon_name] = 0	
	for name, items in liwc_lexicons.iteritems():
		for item in items:
			pattern = re.compile(item)
			count = len(pattern.findall(post))
			liwc_lexicon_to_count[name] += count
		liwc_lexicon_to_count[name] /= float(len(post.split(' ')))
# 		if liwc_lexicon_to_count[name]< 0.0:
# 			print "negative :", post
# 		if name=="positive_affect" and liwc_lexicon_to_count[name] == 1.0:
# 			print "hi: ", post
	return liwc_lexicon_to_count

def get_liwc_dictionary():
	
	liwc_lex_dict = {}
	liwc_lex_dict["positive_affect"] = get_liwc_lexicons("positive_affect")
	liwc_lex_dict["negative_affect"] = get_liwc_lexicons("negative_affect")
	liwc_lex_dict["anger"] = get_liwc_lexicons("anger")
	liwc_lex_dict["anxiety"] = get_liwc_lexicons("anxiety")	
	liwc_lex_dict["sadness"] = get_liwc_lexicons("sadness")
	liwc_lex_dict["swear"] = get_liwc_lexicons("swear")
	return liwc_lex_dict



def get_liwc_lexicons(category):
	liwc_lexicons_directory = "LIWC_lexicons"
	lexicon = []
	lexicon_str = "("
	with open("{0}/{1}".format(liwc_lexicons_directory, category), "r") as file_handle:
		for line in file_handle:
			item = line.strip()
			if "*" in item:
				item = r"\b{0}\b".format(item.replace("*", ".*?"))
			else:
				item = r"\b{0}\b".format(item)
			lexicon_str += item + "|"
	lexicon_str = lexicon_str[:-1] + ")"
	lexicon.append(lexicon_str)
	return lexicon

liwc_dictionary=get_liwc_dictionary()
#print liwc_dictionary


with open("negativeVectors.tsv", "w") as negativeVectors_file:
    for i in range(len(negativeListCopy)):
        outputDictionaryNegative=getLex(negativeListCopy[i], liwc_dictionary)
        negativeVectors_file.write(str(negativeListCopy[i])+"\t"+str(outputDictionaryNegative["negative_affect"])+"\t"+str(outputDictionaryNegative["positive_affect"])+"\t"+str(outputDictionaryNegative["anger"])
                                   +"\t"+str(outputDictionaryNegative["anxiety"])+"\t"+str(outputDictionaryNegative["swear"])+"\t"+str(outputDictionaryNegative["sadness"])+"\n")    

with open("positiveVectors.tsv", "w") as positiveVectors_file:
    for i in range(len(positiveListCopy)):
        outputDictionaryPositive=getLex(positiveListCopy[i], liwc_dictionary)
        positiveVectors_file.write(str(positiveListCopy[i])+"\t"+str(outputDictionaryPositive["negative_affect"])+"\t"+str(outputDictionaryPositive["positive_affect"])+"\t"+str(outputDictionaryPositive["anger"])
                                   +"\t"+str(outputDictionaryPositive["anxiety"])+"\t"+str(outputDictionaryPositive["swear"])+"\t"+str(outputDictionaryPositive["sadness"])+"\n")    


        
print negativeListCopy[0:5]
print positiveListCopy[0:5]
    











['relax fun park loveit sisters', 'travel genie itinerary love fun f4f sun beach woohoo awesome giveaway thank you for the amazing chance', 'love couple couplegoals couples cute girlfriend boyfriend like4like inlove relationshipgoals love', 'you need to learn to be by nature because you ll seldom have the chance to be by circumstance lavetta sue wegman', 'weekend before weekend twodaysholiday']
['i missed it', 'traditional tradionaltattoo traditionaltattoos marinero chile chiletattoo diseodisponible diseodispo', 'dios qu hambre ahora quiero un bocadillo de calamares', 'rip brussels victims why justdontgetit whatswiththehatred brusselsattack', 'terrible brussels']
['relax fun park loveit sisters', 'travel genie itinerary love fun f4f sun beach woohoo awesome giveaway thank you for the amazing chance', 'love couple couplegoals couples cute girlfriend boyfriend like4like inlove relationshipgoals love', 'you need to learn to be by nature because you ll seldom have the chance to be by circu

In [5]:
#part b
#removing stopwords from tweets
import nltk
from nltk.corpus import stopwords

print positiveListCopy[0:5]

def removeStopWords(sentence):
    flitered_word_list=[]
    word_list=sentence.split(' ')
    filtered_word_list = [word for word in word_list if word not in stopwords.words('english')]
    return (' '.join(filtered_word_list)).strip()

filteredNegativeList=[]
filteredPositiveList=[]
for post in negativeListCopy:
#     print post
    filteredNegativeList.append(removeStopWords(post))
for post in positiveListCopy:
#     print post
    filteredPositiveList.append(removeStopWords(post))
    
    
print filteredPositiveList[0:5]
print filteredNegativeList[0:5]

allPostsList=filteredNegativeList+filteredPositiveList

print len(allPostsList)

# print len(filteredNegativeList)
# print len(filteredPositiveList)
# print len(allPostsList)
# print filteredPositiveList[-1]






['relax fun park loveit sisters', 'travel genie itinerary love fun f4f sun beach woohoo awesome giveaway thank you for the amazing chance', 'love couple couplegoals couples cute girlfriend boyfriend like4like inlove relationshipgoals love', 'you need to learn to be by nature because you ll seldom have the chance to be by circumstance lavetta sue wegman', 'weekend before weekend twodaysholiday']
['relax fun park loveit sisters', 'travel genie itinerary love fun f4f sun beach woohoo awesome giveaway thank amazing chance', 'love couple couplegoals couples cute girlfriend boyfriend like4like inlove relationshipgoals love', 'need learn nature seldom chance circumstance lavetta sue wegman', 'weekend weekend twodaysholiday']
['missed', 'traditional tradionaltattoo traditionaltattoos marinero chile chiletattoo diseodisponible diseodispo', 'dios qu hambre ahora quiero un bocadillo de calamares', 'rip brussels victims justdontgetit whatswiththehatred brusselsattack', 'terrible brussels']
23772


In [6]:
#calculating n-grams for all posts
from nltk.util import ngrams
from collections import Counter


listOfUnigrams=[]
listOfBigrams=[]
listOfTrigrams=[]
unigrams=[]
bigrams=[]
trigrams=[]


for post in allPostsList: 
    wordList=post.split(' ')
    unigrams=ngrams(wordList,1)
    bigrams=ngrams(wordList,2)
    if (len(wordList)>3):
        trigrams=ngrams(wordList,3)        
    for unigram in unigrams:
        listOfUnigrams.append(unigram)
    for bigram in bigrams:
        listOfBigrams.append(bigram)
    for trigram in trigrams:
        listOfTrigrams.append(trigram)
        
# print "lenght of trigrams : "+ str(len(listOfTrigrams))
# print "first Trigram is : "+str(listOfTrigrams[0])

fdistUnigrams = nltk.FreqDist(listOfUnigrams)
fdistBigrams =  nltk.FreqDist(listOfBigrams)
fdistTrigrams = nltk.FreqDist(listOfTrigrams)

funi=[]
fbi=[]
ftri=[]

#sort according to the frequencies
for k,v in fdistUnigrams.items():
    funi.append((k,v))
funi.sort(key=lambda tup: tup[1], reverse=True)

for k,v in fdistBigrams.items():
    fbi.append((k,v))
fbi.sort(key=lambda tup: tup[1], reverse=True)

for k,v in fdistTrigrams.items():
    ftri.append((k,v))
ftri.sort(key=lambda tup: tup[1], reverse=True)

#combine all lists of frquency distributions of ngrams
fn=funi+fbi+ftri
print len(fn)

fn.sort(key=lambda tup:tup[1], reverse=True)


# print type(fn)
fn500=[]
fn100=[]
fn50=[]

for k in fn:
    if k[1]>=500:
        fn500.append(k)
    if k[1]>=100:
        fn100.append(k)
    if k[1]>50:
        fn50.append(k)

#here we have list of all ngrams that have frequencies above 50, 100 and 500            

print len(fn500), len(fn50), len(fn100)


284316
17 692 304


In [7]:
# read each post
# find its ngrams
# for the 500 list take first ngram and see if it exists for post 1, if it does, then right its frequency in place. else write 0
# similarly do it for 100list and 50list

def findAllNgrams(tweet):
    wordList=tweet.split(' ')
    listOfUni=[]
    listOfBi=[]
    listOfTri=[]
    unigrams=ngrams(wordList,1)
    bigrams=ngrams(wordList,2)
    trigrams=ngrams(wordList,3)
    for unigram in unigrams:
        listOfUni.append(unigram)
    for bigram in bigrams:
        listOfBi.append(bigram)
    for trigram in trigrams:
        listOfTri.append(trigram)
    return (listOfUni+listOfBi+listOfTri)    

listOfNgramsForaPost=[]
featureVectorhappy500=[]
featureVectorhappy100=[]
featureVectorhappy50=[]
featureVectorsad500=[]
featureVectorsad100=[]
featureVectorsad50=[]


def createStringOfVectors(featureVec):
    featureString='\t'.join(featureVec)
    featureString=featureString.strip()
    return featureString 
    
  
        
def checkTupleMatch(k, listOfngrams):
    #k is a tuple that can be unigram, bigram or trigram
    #listOfngrams contains a list of tuples
    if k in listOfngrams:
        return True;
        
filename="500ngramfeatureFileHappy.tsv"

with open(filename, "w") as vectorFile:
    for post in filteredPositiveList:
        counterOfNgramsForaPost=Counter(findAllNgrams(post))
        for k in fn500:
            #check if k exists in list of all ngrams. If yes add the frequency to the feature vector, else add zero.            
            if k[0] in counterOfNgramsForaPost:
                featureVectorhappy500.append(str(counterOfNgramsForaPost[k[0]]))
            else:
                featureVectorhappy500.append('0')
        featureHappyString=createStringOfVectors(featureVectorhappy500)
        #print(featureVectorhappy500)
        featureVectorhappy500[:]=[]
        
        vectorFile.write(post+"\t"+featureHappyString+"\n")


    
             
    

    
        
       







In [8]:
print len(fn500)

17


In [9]:
def checkTupleMatch(k, listOfngrams):
    #k is a tuple that can be unigram, bigram or trigram
    #listOfngrams contains a list of tuples
    print "insideCheckTupleMatch"
    if k in listOfngrams:
        return True;
l=('love',)
k=[('love','ajkdsfsa'),('love',)]
if checkTupleMatch(l,k):
    print "contains"


insideCheckTupleMatch
contains


In [10]:
print findAllNgrams("this is a check tweet to see if it returns all ngramsS")

[('this',), ('is',), ('a',), ('check',), ('tweet',), ('to',), ('see',), ('if',), ('it',), ('returns',), ('all',), ('ngramsS',), ('this', 'is'), ('is', 'a'), ('a', 'check'), ('check', 'tweet'), ('tweet', 'to'), ('to', 'see'), ('see', 'if'), ('if', 'it'), ('it', 'returns'), ('returns', 'all'), ('all', 'ngramsS'), ('this', 'is', 'a'), ('is', 'a', 'check'), ('a', 'check', 'tweet'), ('check', 'tweet', 'to'), ('tweet', 'to', 'see'), ('to', 'see', 'if'), ('see', 'if', 'it'), ('if', 'it', 'returns'), ('it', 'returns', 'all'), ('returns', 'all', 'ngramsS')]


In [11]:
filename="500ngramfeatureFileSad.tsv"
with open(filename, "w") as vectorFile:
    for post in filteredNegativeList:
        counterOfNgramsForaPost=Counter(findAllNgrams(post))
        for k in fn500:            
            #check if k exists in list of all ngrams. If yes add the frequency to the feature vector, else add zero.            
            if k[0] in counterOfNgramsForaPost:
                featureVectorsad500.append(str(counterOfNgramsForaPost[k[0]]))
            else:
                featureVectorsad500.append('0')
                
        featureSadString=createStringOfVectors(featureVectorsad500)
        print len(featureVectorsad500)
        featureVectorsad500[:]=[]
        
        
        vectorFile.write(post+"\t"+featureSadString+"\n")

17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
1

In [12]:
filename="100ngramfeatureFileHappy.tsv"
with open(filename, "w") as vectorFile:
    for post in filteredPositiveList:
        counterOfNgramsForaPost=Counter(findAllNgrams(post))
        for k in fn100:
            #check if k exists in list of all ngrams. If yes add the frequency to the feature vector, else add zero.            
            if k[0] in counterOfNgramsForaPost:
                
                featureVectorhappy100.append(str(counterOfNgramsForaPost[k[0]]))
            else:
                
                featureVectorhappy100.append('0')
        
        featureHappyString=createStringOfVectors(featureVectorhappy100)
        print len(featureVectorhappy100)
        featureVectorhappy100[:]=[]

        vectorFile.write(post+"\t"+featureHappyString+"\n")

304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304


In [13]:
filename="50ngramfeatureFileHappy.tsv"
with open(filename, "w") as vectorFile:
    for post in filteredPositiveList:
        counterOfNgramsForaPost=Counter(findAllNgrams(post))
        for k in fn50:            
            #check if k exists in list of all ngrams. If yes add the frequency to the feature vector, else add zero.            
            if k[0] in listOfNgramsForaPost:              
                featureVectorhappy50.append(str(counterOfNgramsForaPost[k[0]]))
            else:
                featureVectorhappy50.append('0')
        featureHappyString=createStringOfVectors(featureVectorhappy50)
        print len(featureVectorhappy50)
        featureVectorhappy50[:]=[]

        vectorFile.write(post+"\t"+featureHappyString+"\n")

692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692


In [14]:
filename="100ngramfeatureFileSad.tsv"
with open(filename, "w") as vectorFile:
    for post in filteredNegativeList:
        counterOfNgramsForaPost=Counter(findAllNgrams(post))
        for k in fn100:            
            #check if k exists in list of all ngrams. If yes add the frequency to the feature vector, else add zero.            
            if k[0] in listOfNgramsForaPost:              
                featureVectorsad100.append(str(counterOfNgramsForaPost[k[0]]))
            else:
                featureVectorsad100.append('0')
        featureSadString=createStringOfVectors(featureVectorsad100)
        print len(featureVectorsad100)
        featureVectorsad100[:]=[]
        
        vectorFile.write(post+"\t"+featureSadString+"\n")

304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304


In [15]:
filename="50ngramfeatureFileSad.tsv"
with open(filename, "w") as vectorFile:
    for post in filteredNegativeList:
        counterOfNgramsForaPost=Counter(findAllNgrams(post))
        for k in fn50:            
            #check if k exists in list of all ngrams. If yes add the frequency to the feature vector, else add zero.            
            if k[0] in listOfNgramsForaPost:              
                featureVectorsad50.append(str(counterOfNgramsForaPost[k[0]]))
            else:
                featureVectorsad50.append('0')
        featureSadString=createStringOfVectors(featureVectorsad50)
        print len(featureVectorsad50)
        featureVectorsad50[:]=[]
        
        vectorFile.write(post+"\t"+featureSadString+"\n")

692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692
692


In [16]:
# code for KNN classifer.
#there should be 4 KNN classifers with k=1,10,100 and 1000
from sklearn.cross_validation import StratifiedKFold
import numpy as np
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
def fitKNN(x_train,x_test,y_train,y_test,knn=1,):
    neigh = KNeighborsClassifier(n_neighbors=knn)    
    y_pred = neigh.fit(x_train, y_train).predict(x_test)
    return [accuracy_score(y_test,y_pred), f1_score(y_test,y_pred),recall_score(y_test,y_pred),precision_score(y_test,y_pred)]
    
    
    

#code for Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score
def fitNaiveBayes(x_train,x_test,y_train,y_test):
    clf_NB = GaussianNB()
    y_pred = clf_NB.fit(x_train, y_train).predict(x_test)
    return [accuracy_score(y_test,y_pred), f1_score(y_test,y_pred),recall_score(y_test,y_pred),precision_score(y_test,y_pred)]
#     GaussianNB()
#     now you can use clf.predict(dataRow)


#classifier code for SVM
from sklearn.svm import SVC
def fitSVM(x_train,x_test,y_train,y_test):    
    clf_SVM = SVC()
    y_pred = clf_SVM.fit(x_train, y_train).predict(x_test)
    return [accuracy_score(y_test,y_pred), f1_score(y_test,y_pred),recall_score(y_test,y_pred),precision_score(y_test,y_pred)]
    

    
    




In [17]:
#make a list of lists for all posts
#loading the LIWC data into X and Y
filename="negativeVectors.tsv"
negativeLiwcFeatureVectors=open(filename).read().splitlines()
#print featureVectors[0:10]

X=[]
Y=[]
for vector in negativeLiwcFeatureVectors[0:1000]:
    temp=vector.split('\t')
    temp=temp[1:]
#     print temp
    X.append([float(i) for i in temp])
    Y.append(0)
print X

filename="positiveVectors.tsv"
positiveLiwcFeatureVectors=open(filename).read().splitlines()

for vector in positiveLiwcFeatureVectors[0:1000]:
    temp=vector.split('\t')
    temp=temp[1:]
#     print temp
    X.append([float(i) for i in temp])
    Y.append(1)
    
print len(X)
print len(Y)

print Y

    
    

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.333333333333], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.142857142857, 0.0, 0.142857142857, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0588235294118, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0416666666667, 0.0833333333333, 0.0, 0.0, 0.0, 0.0416666666667], [0.0, 0.0769230769231, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0454545454545, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.1, 0.1, 0.0, 0.0, 0.0, 0.1], [0.0, 0.0, 0.0, 0.0, 0.0, 0.4], [0.0, 0.0384615384615, 0.0, 0.0384615384615, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.133333333333, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0769230769231, 0.0, 0.0769230769231, 0.0769230769231, 0.0769230769231, 0.0], [0.0, 0.181818181818, 0.0, 0.0, 0.0, 0.0909090909091], [0.285714285714, 0.0, 0.0, 0.0714285714286, 0.0, 0.357142857143], [0.125, 0.0, 0.0, 

In [18]:
#preparing training and testing data set for LIWC vectors using KFolds
#finding metrics on all classifiers for liwc data
X, Y= np.array(X), np.array(Y)
k_fold_accuracies_NB = []
k_fold_accuracies_SVM = []
k_fold_accuracies_KNN1 = []
k_fold_accuracies_KNN10 = []
k_fold_accuracies_KNN100 = []
k_fold_accuracies_KNN1000 = []
liwc_scores_NB=[]
liwc_scores_SVM=[]
liwc_scores_KNN1=[]
liwc_scores_KNN10=[]
liwc_scores_KNN100=[]
liwc_scores_KNN1000=[]
skf = StratifiedKFold(Y, n_folds=5)
for train_index, test_index in skf:
    k_fold_accuracies_NB.append(fitNaiveBayes(X[train_index],X[test_index],Y[train_index],Y[test_index]))
    k_fold_accuracies_SVM.append(fitSVM(X[train_index],X[test_index],Y[train_index],Y[test_index]))
    k_fold_accuracies_KNN1.append(fitKNN(X[train_index],X[test_index],Y[train_index],Y[test_index],1))
    k_fold_accuracies_KNN10.append(fitKNN(X[train_index],X[test_index],Y[train_index],Y[test_index],10))
    k_fold_accuracies_KNN100.append(fitKNN(X[train_index],X[test_index],Y[train_index],Y[test_index],100))
    k_fold_accuracies_KNN1000.append(fitKNN(X[train_index],X[test_index],Y[train_index],Y[test_index],1000))
liwc_scores_NB=np.asarray(k_fold_accuracies_NB).mean(axis=0)
liwc_scores_SVM=np.asarray(k_fold_accuracies_SVM).mean(axis=0)
liwc_scores_KNN1=np.asarray(k_fold_accuracies_KNN1).mean(axis=0)
liwc_scores_KNN10=np.asarray(k_fold_accuracies_KNN10).mean(axis=0)
liwc_scores_KNN100=np.asarray(k_fold_accuracies_KNN100).mean(axis=0)
liwc_scores_KNN1000=np.asarray(k_fold_accuracies_KNN1000).mean(axis=0)

print liwc_scores_NB
print liwc_scores_KNN1
print liwc_scores_SVM
print liwc_scores_KNN10
print liwc_scores_KNN100
print liwc_scores_KNN1000

[ 0.6345      0.72023985  0.941       0.5834193 ]
[ 0.617       0.46256845  0.34        0.75901795]
[ 0.6585      0.53423076  0.393       0.83749887]
[ 0.639       0.4921729   0.364       0.80950715]
[ 0.6815      0.64005314  0.567       0.73729948]
[ 0.6705      0.61804387  0.535       0.73580524]


In [19]:
#loading data for d>=500
filename="500ngramfeatureFileSad.tsv"
negativeNgramFeatureVectors=[]
negativeNgramFeatureVectors=open(filename).read().splitlines()
print negativeNgramFeatureVectors[0:10]

X=[]
Y=[]
for vector in negativeNgramFeatureVectors:
    temp=vector.split('\t')
    temp=temp[1:]
#     print temp
    X.append([float(i) for i in temp])
    Y.append(0)
print X

filename="500ngramfeatureFileHappy.tsv"
positiveNgramFeatureVectors=open(filename).read().splitlines()
print positiveNgramFeatureVectors[0:10]

for vector in positiveNgramFeatureVectors:
    temp=vector.split('\t')
    temp=temp[1:]
#     print temp
    X.append([float(i) for i in temp])
    Y.append(1)
    


#print Y
print len(X)
print len(Y)


['missed\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0', 'traditional tradionaltattoo traditionaltattoos marinero chile chiletattoo diseodisponible diseodispo\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0', 'dios qu hambre ahora quiero un bocadillo de calamares\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0', 'rip brussels victims justdontgetit whatswiththehatred brusselsattack\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0', 'terrible brussels\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0', 'belgique triste\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0', 'may beautiful morning many poor travellers feeling tonight brusselsattack\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0', 'sorry face sorry charlie oyster bar sorrycharliesoysterbar savannah tourism tour tourist mexican\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0', 'tech give gift bitcoin christmas bitcoin gift ideas\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0', 'world anyway\t0\t0\t0\t0

In [20]:
X, Y= np.array(X), np.array(Y)


k_fold_accuracies_NB[:] = []
k_fold_accuracies_SVM[:] = []
k_fold_accuracies_KNN1[:] = []
k_fold_accuracies_KNN10[:] = []
k_fold_accuracies_KNN100[:] = []
k_fold_accuracies_KNN1000[:] = []
d500_scores_NB=[]
d500_scores_SVM=[]
d500_scores_KNN1=[]
d500_scores_KNN10=[]
d500_scores_KNN100=[]
d500_scores_KNN1000=[]
skf = StratifiedKFold(Y, n_folds=5)
for train_index, test_index in skf:
    k_fold_accuracies_NB.append(fitNaiveBayes(X[train_index],X[test_index],Y[train_index],Y[test_index]))
    k_fold_accuracies_SVM.append(fitSVM(X[train_index],X[test_index],Y[train_index],Y[test_index]))
    k_fold_accuracies_KNN1.append(fitKNN(X[train_index],X[test_index],Y[train_index],Y[test_index],1))
    k_fold_accuracies_KNN10.append(fitKNN(X[train_index],X[test_index],Y[train_index],Y[test_index],10))
    k_fold_accuracies_KNN100.append(fitKNN(X[train_index],X[test_index],Y[train_index],Y[test_index],100))
    k_fold_accuracies_KNN1000.append(fitKNN(X[train_index],X[test_index],Y[train_index],Y[test_index],1000))
d500_scores_NB=np.asarray(k_fold_accuracies_NB).mean(axis=0)
d500_scores_SVM=np.asarray(k_fold_accuracies_SVM).mean(axis=0)
d500_scores_KNN1=np.asarray(k_fold_accuracies_KNN1).mean(axis=0)
d500_scores_KNN10=np.asarray(k_fold_accuracies_KNN10).mean(axis=0)
d500_scores_KNN100=np.asarray(k_fold_accuracies_KNN100).mean(axis=0)
d500_scores_KNN1000=np.asarray(k_fold_accuracies_KNN1000).mean(axis=0)

print d500_scores_NB
print d500_scores_KNN1
print d500_scores_SVM
print d500_scores_KNN10
print d500_scores_KNN100
print d500_scores_KNN1000

[ 0.65337424  0.47189607  0.34735684  0.73596375]
[ 0.58863396  0.18449411  0.10459351  0.81162123]
[ 0.66738279  0.51125144  0.39036459  0.74113325]
[ 0.5989396   0.19832142  0.11147723  0.91325663]
[ 0.62426412  0.28956755  0.17183964  0.92320786]
[ 0.58796021  0.27230584  0.17325038  0.64035553]


In [21]:
def loadDataForClassification(fileNamePositive,fileNameNegative,n):
    nFeatureVectors=[]
    temp=[]
    X=[]
    Y=[]
    nFeatureVectors=open(fileNameNegative).read().splitlines()
    for vector in nFeatureVectors[0:n]:
        temp=vector.split('\t')
        temp=temp[1:]
        X.append([float(i) for i in temp])
        Y.append(0)
    temp[:]=[]
    pFeatureVectors=open(fileNamePositive).read().splitlines()
    for vector in pFeatureVectors[0:n]:
        temp=vector.split('\t')
        temp=temp[1:]
        X.append([float(i) for i in temp])
        Y.append(1)
    return [X,Y]

dataset=loadDataForClassification("positiveVectors.tsv","negativeVectors.tsv",1000)
X=dataset[0]
Y=dataset[1]
print X

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.333333333333], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.142857142857, 0.0, 0.142857142857, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0588235294118, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0416666666667, 0.0833333333333, 0.0, 0.0, 0.0, 0.0416666666667], [0.0, 0.0769230769231, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0454545454545, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.1, 0.1, 0.0, 0.0, 0.0, 0.1], [0.0, 0.0, 0.0, 0.0, 0.0, 0.4], [0.0, 0.0384615384615, 0.0, 0.0384615384615, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.133333333333, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0769230769231, 0.0, 0.0769230769231, 0.0769230769231, 0.0769230769231, 0.0], [0.0, 0.181818181818, 0.0, 0.0, 0.0, 0.0909090909091], [0.285714285714, 0.0, 0.0, 0.0714285714286, 0.0, 0.357142857143], [0.125, 0.0, 0.0, 

In [22]:
def calculateAllScores(X,Y):
    X, Y= np.array(X), np.array(Y)    
    k_fold_accuracies_NB = []
    k_fold_accuracies_SVM = []
    k_fold_accuracies_KNN1 = []
    k_fold_accuracies_KNN10 = []
    k_fold_accuracies_KNN100 = []
    k_fold_accuracies_KNN1000 = []
    scores_NB=[]
    scores_SVM=[]
    scores_KNN1=[]
    scores_KNN10=[]
    scores_KNN100=[]
    scores_KNN1000=[]
    skf = StratifiedKFold(Y, n_folds=5)
    for train_index, test_index in skf:
        k_fold_accuracies_NB.append(fitNaiveBayes(X[train_index],X[test_index],Y[train_index],Y[test_index]))
        k_fold_accuracies_SVM.append(fitSVM(X[train_index],X[test_index],Y[train_index],Y[test_index]))
        k_fold_accuracies_KNN1.append(fitKNN(X[train_index],X[test_index],Y[train_index],Y[test_index],1))
        k_fold_accuracies_KNN10.append(fitKNN(X[train_index],X[test_index],Y[train_index],Y[test_index],10))
        k_fold_accuracies_KNN100.append(fitKNN(X[train_index],X[test_index],Y[train_index],Y[test_index],100))
        k_fold_accuracies_KNN1000.append(fitKNN(X[train_index],X[test_index],Y[train_index],Y[test_index],1000))
    scores_NB=np.asarray(k_fold_accuracies_NB).mean(axis=0)
    scores_SVM=np.asarray(k_fold_accuracies_SVM).mean(axis=0)
    scores_KNN1=np.asarray(k_fold_accuracies_KNN1).mean(axis=0)
    scores_KNN10=np.asarray(k_fold_accuracies_KNN10).mean(axis=0)
    scores_KNN100=np.asarray(k_fold_accuracies_KNN100).mean(axis=0)
    scores_KNN1000=np.asarray(k_fold_accuracies_KNN1000).mean(axis=0)

    return [scores_NB,scores_KNN1,scores_SVM,scores_KNN10,scores_KNN100,scores_KNN1000]

In [23]:
liwcDataset=loadDataForClassification("positiveVectors.tsv","negativeVectors.tsv",1000)
d500Dataset=loadDataForClassification("500ngramfeatureFileHappy.tsv","500ngramfeatureFileSad.tsv",1000)
d100Dataset=loadDataForClassification("100ngramfeatureFileHappy.tsv","100ngramfeatureFileSad.tsv",1000)
d50Dataset=loadDataForClassification("50ngramfeatureFileHappy.tsv","50ngramfeatureFileSad.tsv",1000)
X_liwc, Y_liwc=liwcDataset[0], liwcDataset[1]
X_d500, Y_d500=d500Dataset[0], d500Dataset[1]
X_d100, Y_d100=d100Dataset[0], d100Dataset[1]
X_d50, Y_d50=d50Dataset[0], d50Dataset[1]

liwcAllScores=calculateAllScores(X_liwc,Y_liwc)
d500AllScores=calculateAllScores(X_d500,Y_d500)
d100AllScores=calculateAllScores(X_d100,Y_d100)
d50AllScores=calculateAllScores(X_d50,Y_d50)



C:\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Anaconda2\lib\site-packages\sklearn\naive_bayes.py:393: RuntimeWarning: divide by zero encountered in log
  n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
C:\Anaconda2\lib\site-packages\sklearn\naive_bayes.py:395: RuntimeWarning: invalid value encountered in divide
  (self.sigma_[i, :]), 1)


In [24]:
print liwcAllScores
print d500AllScores
print d100AllScores
print d50AllScores

[array([ 0.6345    ,  0.72023985,  0.941     ,  0.5834193 ]), array([ 0.617     ,  0.46256845,  0.34      ,  0.75901795]), array([ 0.6585    ,  0.53423076,  0.393     ,  0.83749887]), array([ 0.639     ,  0.4921729 ,  0.364     ,  0.80950715]), array([ 0.6815    ,  0.64005314,  0.567     ,  0.73729948]), array([ 0.6705    ,  0.61804387,  0.535     ,  0.73580524])]
[array([ 0.6225    ,  0.43373151,  0.291     ,  0.86595873]), array([ 0.5825    ,  0.32783691,  0.209     ,  0.82969926]), array([ 0.634     ,  0.49870894,  0.365     ,  0.79424652]), array([ 0.593     ,  0.34754274,  0.219     ,  0.870409  ]), array([ 0.5515    ,  0.30888043,  0.201     ,  0.67467865]), array([ 0.543     ,  0.20187556,  0.117     ,  0.80294118])]
[array([ 0.9345    ,  0.92976253,  0.869     ,  1.        ]), array([ 0.922     ,  0.91527516,  0.844     ,  1.        ]), array([ 0.593     ,  0.31337941,  0.186     ,  1.        ]), array([ 0.9335    ,  0.92862691,  0.867     ,  1.        ]), array([ 0.9335    ,  

In [25]:
#display the Accuracy in the form of a table
from tabulate import tabulate

def displayTable(name,pos):
    
    AllAccuracies=[]
    tempAccuracy=[]
    tempAccuracy.append("LIWC")
    for i in liwcAllScores:
        tempAccuracy.append(i[pos])
    AllAccuracies.append(tempAccuracy)
    tempAccuracy=[]

    tempAccuracy.append("nGram>500")
    for i in d500AllScores:
        tempAccuracy.append(i[pos])
    AllAccuracies.append(tempAccuracy)
    tempAccuracy=[]

    tempAccuracy.append("nGram>100")
    for i in d100AllScores:
        tempAccuracy.append(i[pos])
    AllAccuracies.append(tempAccuracy)
    tempAccuracy=[]

    tempAccuracy.append("nGram>50")
    for i in d50AllScores:
        tempAccuracy.append(i[pos])
    AllAccuracies.append(tempAccuracy)
    tempAccuracy=[]

    print name
    headers=["Naive Bayes", "SVM", "KNN k=1", "KNN k=10", "KNN k=100", "KNN k=1000"]

    print tabulate(AllAccuracies, headers, tablefmt="grid")

In [26]:
displayTable("ACCURACY TABLE",0)

ACCURACY TABLE
+-----------+---------------+--------+-----------+------------+-------------+--------------+
|           |   Naive Bayes |    SVM |   KNN k=1 |   KNN k=10 |   KNN k=100 |   KNN k=1000 |
+===========+===============+========+===========+============+=============+==============+
| LIWC      |        0.6345 | 0.617  |    0.6585 |     0.639  |      0.6815 |       0.6705 |
+-----------+---------------+--------+-----------+------------+-------------+--------------+
| nGram>500 |        0.6225 | 0.5825 |    0.634  |     0.593  |      0.5515 |       0.543  |
+-----------+---------------+--------+-----------+------------+-------------+--------------+
| nGram>100 |        0.9345 | 0.922  |    0.593  |     0.9335 |      0.9335 |       0.5    |
+-----------+---------------+--------+-----------+------------+-------------+--------------+
| nGram>50  |        0.5    | 0.5    |    0.5    |     0.5    |      0.5    |       0.5    |
+-----------+---------------+--------+-----------+-----

In [27]:
displayTable("PRECISION Scores",3)

PRECISION Scores
+-----------+---------------+----------+-----------+------------+-------------+--------------+
|           |   Naive Bayes |      SVM |   KNN k=1 |   KNN k=10 |   KNN k=100 |   KNN k=1000 |
+===========+===============+==========+===========+============+=============+==============+
| LIWC      |      0.583419 | 0.759018 |  0.837499 |   0.809507 |    0.737299 |     0.735805 |
+-----------+---------------+----------+-----------+------------+-------------+--------------+
| nGram>500 |      0.865959 | 0.829699 |  0.794247 |   0.870409 |    0.674679 |     0.802941 |
+-----------+---------------+----------+-----------+------------+-------------+--------------+
| nGram>100 |      1        | 1        |  1        |   1        |    1        |     0        |
+-----------+---------------+----------+-----------+------------+-------------+--------------+
| nGram>50  |      0        | 0        |  0.5      |   0        |    0        |     0.5      |
+-----------+---------------+----

In [28]:
displayTable("RECALL Scores",2)

RECALL Scores
+-----------+---------------+-------+-----------+------------+-------------+--------------+
|           |   Naive Bayes |   SVM |   KNN k=1 |   KNN k=10 |   KNN k=100 |   KNN k=1000 |
+===========+===============+=======+===========+============+=============+==============+
| LIWC      |         0.941 | 0.34  |     0.393 |      0.364 |       0.567 |        0.535 |
+-----------+---------------+-------+-----------+------------+-------------+--------------+
| nGram>500 |         0.291 | 0.209 |     0.365 |      0.219 |       0.201 |        0.117 |
+-----------+---------------+-------+-----------+------------+-------------+--------------+
| nGram>100 |         0.869 | 0.844 |     0.186 |      0.867 |       0.867 |        0     |
+-----------+---------------+-------+-----------+------------+-------------+--------------+
| nGram>50  |         0     | 0     |     1     |      0     |       0     |        1     |
+-----------+---------------+-------+-----------+------------+----

In [29]:
displayTable("F1 Scores",1)

F1 Scores
+-----------+---------------+----------+-----------+------------+-------------+--------------+
|           |   Naive Bayes |      SVM |   KNN k=1 |   KNN k=10 |   KNN k=100 |   KNN k=1000 |
+===========+===============+==========+===========+============+=============+==============+
| LIWC      |      0.72024  | 0.462568 |  0.534231 |   0.492173 |    0.640053 |     0.618044 |
+-----------+---------------+----------+-----------+------------+-------------+--------------+
| nGram>500 |      0.433732 | 0.327837 |  0.498709 |   0.347543 |    0.30888  |     0.201876 |
+-----------+---------------+----------+-----------+------------+-------------+--------------+
| nGram>100 |      0.929763 | 0.915275 |  0.313379 |   0.928627 |    0.928627 |     0        |
+-----------+---------------+----------+-----------+------------+-------------+--------------+
| nGram>50  |      0        | 0        |  0.666667 |   0        |    0        |     0.666667 |
+-----------+---------------+----------+

In [30]:
a = ['the','the frog','and','the','the princess']
b = 'the'


In [31]:
#calculate baseline accuracy
lengthHappyPosts=len(filteredPositiveList)
totalLength=len(allPostsList)
chanceAccuracy=float(lengthHappyPosts)/totalLength
print chanceAccuracy

0.446028941612


# Report

## Question 3
### a. Compare your classification models to chance model of this dataset



### b. Why do you think some classifiers perform better than the others?
 We have used KNN, SVM and Naive Bayes classifiers and from the tables we obtained, we can see that certain classifiers perform better than others. This is true for all datasets and not just the current one in use. The performance of classifiers depends on a number of things including the type of the data set, the number of data points and values of the tuning parameters. While KNN is better for data points that show clustering behaviour, but it needs to be carefully tuned. Depending on the value of K, accuracies can vary. It also doesn't perform well when there are many data points. SVM is a very popular algorithm which works better with a limited set of points in a high dimensional space. SVM is good with outliers as it will only use the most relevant points to find a linear separation (support vectors). Naive Bayes on the other hand, assumes that the data points are conditionally independent. If that is not the case and there are some hidden correlated attributes, then the performance of NAive Bayes algorithm will be greatly hampered. 
 

### c. How do the different feature choices impact classifier performance? 

Features are like decision points. Every data-point is represented using a set of features. These features in turn help the machine decide which data point it is. For some data classes, certain types of features are uniquely associated and must be included for good performance of a classifier. For example, if you are classifying between dogs and cats and you do not include the size of the animal, or the ear-length of the animal as feature (dogs are usually larger than cats and they have longer ears), then the classifer performance will certainly go down. In the paper, "Impact of Feature Selection Techniques for Tweet Sentiment Classification", Prusa et. al have looked this feature selection problem specifically for sentiment analyses of tweets. This paper has evaluated the performance of ten filter-based feature ranking techniques on tweets labelled as positive and negative.There results show that sentiment classification can indeed be greatly affected by feature selection. 
They report that, " In particular five feature ranking techniques (Chi-Squared, the Kolmogorov-Smirnov statistic, Mutual Information, area under the Precision-Recall curve, and area under the Receiver Operating Characteristic curve) improve classification performance over no feature selection". Moreover the authors also show that using 75-200 features can improve classification results on a whole. 